version: '2'

networks:
  kazenokumo:
    driver: bridge

services:
  web:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8000:80"
      - "8001:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - message-server
    networks:
      - kazenokumo
  message-server:
    container_name: kaze-server
    build:
      dockerfile: Dockerfile
    image: kazenokumo/bmi
#    volumes:
#      - ./:/var/www
    ports:
      - 18888:8080
    expose:
      - "8080"
    networks:
      - kazenokumo